name: Tweet Random Lyric
on:
  push:
    branches:
      - main  # Adjust the branch name as needed
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: executing python script
        env:
            MUSIXMATCH_API_KEY: ${{ secrets.MUSIXMATCH_API_KEY }}
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
            CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        run: python lyrics.py







  

