name: Twitter Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [main]

jobs:
  run_bot:
    runs-on: windows-latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Debug Print Environment Variables
        run: |
          echo "CONSUMER_KEY: $CONSUMER_KEY"
          echo "CONSUMER_SECRET: $CONSUMER_SECRET"
          echo "ACCESS_TOKEN: $ACCESS_TOKEN"
          echo "ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET"

      - name: Run Twitter Bot
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          MUSIXMATCH_API_KEY: ${{ secrets.MUSIXMATCH_API_KEY }}
        run: python lyrics.py



  

