name: Tweet Random Lyric

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
      
jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Musixmatch API Key
        env: 
          musixmatch-api-key: ${{ secrets.MUSIXMATCH_API_KEY }}

      - name: Get random lyric
        id: get_lyric
        run: |
          python lyrics.py
          echo "::set-output name=lyric::$(cat random_lyric.txt)"

      - name: Send Tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ steps.get_lyric.outputs.lyric }}
          consumer-key: ${{ secrets.CONSUMER_KEY }}
          consumer-secret: ${{ secrets.CONSUMER_SECRET }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.ACCESS_TOKEN_SECRET }}









  

