name: Twitter Bot

on:
  push:
    branches: [main]

jobs:
  run_bot:
    runs-on: ubuntu-latest
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      MUSIXMATCH_API_KEY: ${{ secrets.MUSIXMATCH_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Random Lyric
        id: random_lyric
        run: |
          echo "Random Lyric::$(python musixmatch.py)" >> $GITHUB_ENV

      - name: Debug Print Random Lyric
        run: |
          echo "Random Lyric: $Random Lyric"

      - name: Tweet
        uses: snow-actions/tweet@v1.4.0
        with:
          status: |
            ${{ steps.random_lyric.outputs.random_lyric }}





  

