name: Tweet Random Lyric

on:
  push:
    branches:
      - main 
jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get and tweet random lyric
        env:
          CONSUMER_API_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          random_lyric=$(python lyrics.py)
          echo "Random Lyric: $random_lyric"
          snow-actions/tweet@v1.4.0 --status "$random_lyric"







  

