name: Tweet Random Lyric

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
      
jobs:
  tweet:
    runs-on: ubuntu-latest
    env:
      MUSIXMATCH_API_KEY: ${{ secrets.MUSIXMATCH_API_KEY }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Musixmatch API Key
        run: |
          echo "MUSIXMATCH_API_KEY=${{ secrets.MUSIXMATCH_API_KEY }}" >> $GITHUB_ENV

      - name: Get random lyric
        id: get_lyric
        run: |
           lyric=$(python lyrics.py)
           echo "::set-output name=lyric::$lyric"

      - name: Send Tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ steps.get_lyric.outputs.lyric }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}










  

